name = "UI Navigation"
description = "A multilingual theme designed for accessibility rather than visual."
license = "MIT"
homepage = "https://github.com/harrymkt/zluinav"
min_version = "0.19.2"
demo = "https://harrymkt.github.io/zluinav"

[extra]
  # The language search path
  tr_path = "langs"
  # Title separator, such as dash (-)
  title_sep = " â€“ "

[author]
  name = "Harry Min Khant"
  homepage = "https://harrymkt.github.io"