name = "UI Navigation"
description = "A theme designed for accessibility rather than visual"
license = "MIT"
homepage = "https://github.com/harrymkt/zluinav"
# The minimum version of Zola required
min_version = "0.4.0"
demo = "https://harrymkt.github.io"

[extra]
# The theme author info.
[author]
name = "Harry Min Khant"
homepage = "https://harrymkt.github.io"