name="Burmese"
acc_title="သုံးစွဲနိုင်မှုလင့်ခ်များ"
acc_skip_main="အဓိကအကြောင်းအရာသို့ ကျော်သွားပါ။"
acc_skip_nav="လမ်းညွှန်မှုသို့ ကျော်သွားပါ။"
acc_skip_footer="အောက်ခြေမှတ်စုသို့ ကျော်သွားပါ။"
main_menu="ပင်မမီနူး"
pagination_title="Pagination"
pagination_first="ပထမစာမျက်နှာ"
pagination_previous="ယခင်စာမျက်နှာ"
pagination_next="နောက်စာမျက်နှာ"
pagination_last="နောက်ဆုံးစာမျက်နှာ"
nav1="အိမ်သို့စတင်ပါ။"
nav2="ဘလော့"