name="Burmese"
acc_skip_main="အဓိကအကြောင်းအရာသို့ ကျော်သွားပါ။"
acc_skip_nav="လမ်းညွှန်မှုသို့ ကျော်သွားပါ။"
acc_skip_footer="အောက်ခြေမှတ်စုသို့ ကျော်သွားပါ။"
main_menu="ပင်မမီနူး"
author="စာရေးသူ"
authors="စာရေးဆရာများ"
updated="အပ်ဒိတ်ရက်စွဲ"
published="ထုတ်ပြန်သည့်ရက်စွဲ"
pagination_title="Pagination"
pagination_first="ပထမစာမျက်နှာ"
pagination_previous="ယခင်စာမျက်နှာ"
pagination_next="နောက်စာမျက်နှာ"
pagination_last="နောက်ဆုံးစာမျက်နှာ"
nav1="အိမ်သို့စတင်ပါ။"
nav2="ဘလော့"